version: "3.9"

services:
  zaidvc:
    build: .
    image: zaid:${TAG}
    container_name: zaid
    network_mode: bridge
    pull_policy: never

networks:
  default: 
    external: true
    name: bridge
  
